### ISSUE TITLE
Error when launching baseline/download_data.py

### ISSUE THREAD

**Issue by emap78** [turpaultn/DCASE2019_task4#15]
There seems to be a problem in `download_data.py`: after launching it from the baseline folder, the following error appears: 

```
INFO - Download_data
 INFO -
Once database is downloaded, do not forget to check your missing_files

INFO - You can change N_JOBS and CHUNK_SIZE to increase the download with more processes.
INFO - Validation data
 0%|                                                                                                                                                               | 0/1168 [00:00<?, ?it/s]/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/site-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
[E] AudioContainer: Stop parameter exceeds file length [tmp/0lNm9pXXHxA.m4a]    (audio.py:779)
NoneType: None
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "download_data.py", line 79, in download_file
    start=float(segment_start), stop=float(segment_end))
  File "/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/site-packages/dcase_util/containers/audio.py", line 780, in load
    raise IOError(message)
OSError: AudioContainer: Stop parameter exceeds file length [tmp/0lNm9pXXHxA.m4a]
"""[D] Y1easzswv0OM_130.000_140.000.wav

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download_data.py", line 215, in <module>
    base_dir_missing_files=base_missing_files_folder)
  File "download_data.py", line 155, in download
    for val in tqdm(p.imap_unordered(download_file_alias, filenames, chunk_size), total=len(filenames)):
  File "/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/site-packages/tqdm/std.py", line 1108, in __iter__
    for obj in iterable:
  File "/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/multiprocessing/pool.py", line 347, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/a3lab/anaconda3/envs/dcase2019/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: AudioContainer: Stop parameter exceeds file length [tmp/0lNm9pXXHxA.m4a]
  0%|                                                                                                                                                               | 0/1168 [00:01<?, ?it/s]
```

I am using the Anaconda environment created with `conda_create_environment.sh` on Ubuntu 18.04.1 LTS, with youtube-dl 2020.3.24, and dcase-util 0.2.11.

**Comment by roytalman** [comment]
I had the same issue, it when download it from 2020 challenge git
https://project.inria.fr/desed/dcase-challenge/dcase-2020-task-4/

**Comment by turpaultn** [comment]
I need to dig more into the issue, but I already had this issue, it seems to be a problem with the audio format (best audio from youtube-dl).
In the meantime, you can always add `OSError` line 97.
I'm just afraid too many files will have an error then after.

**Comment by zhyj3038** [comment]
the error occurs when length of  the downloading video  is shorter than (offset - onsset),  just add a "try ... except" to fix the bug

**Comment by turpaultn** [comment]
@zhyj3038 I agree, so as I suggested earlier, I'll add the `OSError`in the except line 97 hoping not too many files would be failing with this error.
